# config.yaml
train_path: "data/train_data_afterCDCDSP.pkl"
test_path: "data/test_data_afterCDCDSP.pkl"
Rs: 40   # train symbol rate
Nch: 1   # train Nch

# model setting
model_name: "SymHoPBC"
model info:
  L: 100
  rho: 1
  steps: 2



# training details
epochs: 200
save_interval: 10
iters_per_batch: 1
batchs: 23                  # number of batch
tbpl: 4000                  # batch size
train_discard: 2000
ber_discard: 10000
lr: 0.001
loss_type: "MT"
opt: "Adagrad"
weight_decay: 0
lamb: 0
device: "cuda:0"

tensorboard_path: "_outputs/log_tensorboard/Rs40_Nch1/SymHoPBC/L100_rho1_steps2_adagrad_lr1e-3"
model_path: "_models/Rs40_Nch1/SymHoPBC/L100_rho1_steps2_adagrad_lr1e-3"
