# config.yaml
train_path: "data/train_data_afterCDCDSP.pkl"
test_path: "data/test_data_afterCDCDSP.pkl"
Rs: 80   # train symbol rate
Nch: 1   # train Nch

# model setting
model_name: "SymFoPBCNN"
model info:
  L: 400
  rho: 1
  index_type: "A"
  hidden_size: [2, 20]
  dropout: 0.5
  activation: 'leaky_relu'
  use_bias: True

# training details
seed: 12123
epochs: 400
save_interval: 10
iters_per_batch: 1
batchs: 23                  # number of batch
tbpl: 4000                  # batch size
train_discard: 2000
ber_discard: 10000
lr: 0.001
loss_type: "MT"
opt: "Adagrad"
weight_decay: 0
lamb: 0
device: "cuda:0"

tensorboard_path: "_outputs/log_tensorboard/Rs80_Nch1/SymFoPBCNN/L400_rho1_index_typeA_train11(adagrad_lr1e-3)"
model_path: "_models/Rs80_Nch1/SymFoPBCNN/L400_rho1_index_typeA_train11(adagrad_lr1e-3)"

# train6: init zero 前两个线性层  (这种初始化最好，为什么？最终选择这种初始化)
# train5: init zero 三个线性层
# train0: init zero 第三个线性层
