# config.yaml
train_path: "data/train_data_afterCDCDSP.pkl"
test_path: "data/test_data_afterCDCDSP.pkl"
Rs: 80   # train symbol rate
Nch: 1   # train Nch

# model setting
model_name: "SoPBC"
model info:
  L: 100
  rho: 1
  Lk: 3
  index_type: "A"
  L1:  400
  rho1: 1

# training details
epochs: 100
save_interval: 10
iters_per_batch: 1
batchs: 23                  # number of batch
tbpl: 4000                  # batch size
train_discard: 2000
ber_discard: 10000
lr: 0.0001
loss_type: "MT"
opt: "Adam"
weight_decay: 0.001
lamb: 0
device: "cuda:0"

tensorboard_path: "_outputs/log_tensorboard/Rs80_Nch1/SoPBC/L100_rho1_Lk3_index_typeA_wdk0.001"
model_path: "_models/Rs80_Nch1/SoPBC/L100_rho1_Lk3_index_typeA_wdk0.001"