# config.yaml
train_path: "data/train_data_afterCDCDSP.pkl"
test_path: "data/test_data_afterCDCDSP.pkl"
Rs: 40   # train symbol rate
Nch: 1   # train Nch

# model setting
model_name: "SoPBC"
model info:
  L: 20
  rho: 1
  Lk: 5
  index_type: "A"
  L1:  100
  rho1: 1

# training details
epochs: 200
save_interval: 10
iters_per_batch: 1
batchs: 23                  # number of batch
tbpl: 4000                  # batch size
train_discard: 2000
ber_discard: 10000
lr: 0.0001
loss_type: "MT"
opt: "Adam"
weight_decay: 0
lamb: 0
device: "cuda:0"

tensorboard_path: "_outputs/log_tensorboard/Rs40"
_Nch1/SoPBC/L20_Lk5_L1(200)_rho1_index_typeAmodel_path: "_models/Rs40"_Nch1/SoPBC/L20_Lk5_L1(200)_rho1_index_typeA