# config.yaml
train_path: "data/train_data_afterCDCDSP.pkl"
test_path: "data/test_data_afterCDCDSP.pkl"
Rs: 80   # train symbol rate
Nch: 1   # train Nch

# model setting
model_name: "SymFoPBCNN"
model info:
  L: 400
  rho: 1
  index_type: "A"
  hidden_size: [2, 10]
  dropout: 0.5
  activation: 'leaky_relu'

# training details
epochs: 100
save_interval: 10
iters_per_batch: 1
batchs: 48                  # number of batch
tbpl: 2000                  # batch size
train_discard: 2000
ber_discard: 10000
loss_type: "MT"
lamb: 0
device: "cuda:0"

opt: "Adam"
opt info:
  lr: 0.0001
  weight_decay: 0

tensorboard_path: "_outputs/log_tensorboard/Rs80_Nch1/SymFoPBCNN/L400_rho1_index_typeA_train1"
model_path: "_models/Rs80_Nch1/SymFoPBCNN/L400_rho1_index_typeA_train1"