# config.yaml
train_path: "data/train_data_afterCDCDSP.pkl"
test_path: "data/test_data_afterCDCDSP.pkl"
Rs: 80   # train symbol rate
Nch: 1   # train Nch
Pch: [2] 

# model setting
model_name: "SymFoPBC"
model info:
  L: 400
  rho: 1
  index_type: "A"

# training details
epochs: 200
save_interval: 10
iters_per_batch: 1
batchs: 23                  # number of batch
tbpl: 4000                  # batch size
train_discard: 2000
ber_discard: 10000
loss_type: "Mean"
lamb: 0
device: "cuda:0"

opt: "Adam"
opt info:
  lr: 0.00001
  weight_decay: 0

tensorboard_path: "_outputs/log_tensorboard/Rs80_Nch1/SymFoPBC/L400_rho1_Pch2"
model_path: "_models/Rs80_Nch1/SymFoPBC/L400_rho1_Pch2"