# config.yaml
train_path: "data/train_data_afterCDCDSP.pkl"
test_path: "data/test_data_afterCDCDSP.pkl"
Rs: 40   # train symbol rate
Nch: 1   # train Nch

# model setting
model_name: "SymFoPBC"
model info:
  L: 40
  rho: 1
  index_type: "A"

# training details
epochs: 100
save_interval: 10
iters_per_batch: 1
batchs: 23                  # number of batch
tbpl: 4000                  # batch size
train_discard: 2000
ber_discard: 10000
lr: 0.0001
loss_type: "MT"
opt: "Adam"
weight_decay: 0
lamb: 0
device: "cuda:0"

tensorboard_path: "_outputs/log_tensorboard/Rs40_Nch1/SymFoPBC/L40_rho1_index_typeA_train1"
model_path: "_models/Rs40_Nch1/SymFoPBC/L40_rho1_index_typeA_train1"